### ISSUE TITLE
Plurals form the gettext way

### ISSUE THREAD

**Issue by manuco** [weirdandwry/nr-local-spa#2]
Hello,

Do you plan to use the gettext plural feature ? https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html

IMHO it is required to translate French the right way since 0 is plural in English and singular in french.

**Comment by carloscm** [comment]
The game does not use gettext. It only uses the PO file format as a convenience.

Plurals already have multiple translations strings for the 1 vs N case (and 0 where it makes sense). See for example "﻿﻿﻿train_total_price_1" or "crossings_n_0".

**Comment by manuco** [comment]
Ok, thanks for the answer.
